/**
 * Technology synonym groups (PRD §6.3).
 *
 * Pure data, no imports — extending this is a data edit, not a code change. The **first
 * variant in each group is the canonical form**; everything else folds into it.
 */
export const TECHNOLOGY: readonly (readonly string[])[] = [
	// Languages
	['javascript', 'js', 'ecmascript'],
	['typescript', 'ts'],
	['python', 'py', 'python3'],
	['java'],
	['c++', 'cpp', 'cplusplus'],
	['c#', 'csharp', 'c-sharp', 'dotnet', '.net'],
	['go', 'golang'],
	['rust', 'rustlang'],
	['ruby', 'rb'],
	['php'],
	['swift'],
	['kotlin', 'kt'],
	['scala'],
	['r'],
	['matlab'],
	['perl'],
	['bash', 'shell', 'sh', 'zsh'],
	['sql'],
	['objective-c', 'objc'],
	['elixir'],
	['haskell'],
	['clojure'],

	// Frontend frameworks
	['react', 'react.js', 'reactjs'],
	['angular', 'angularjs', 'angular.js'],
	['vue', 'vue.js', 'vuejs'],
	['svelte', 'sveltekit'],
	['next.js', 'nextjs', 'next'],
	['nuxt', 'nuxt.js', 'nuxtjs'],
	['jquery'],
	['redux'],
	['tailwind', 'tailwindcss'],
	['bootstrap'],
	['html', 'html5'],
	['css', 'css3'],
	['sass', 'scss'],
	['webpack'],
	['vite'],

	// Backend
	['node.js', 'nodejs', 'node'],
	['express', 'express.js', 'expressjs'],
	['django'],
	['flask'],
	['fastapi'],
	['spring', 'spring boot', 'springboot'],
	['rails', 'ruby on rails', 'ror'],
	['laravel'],
	['asp.net', 'aspnet'],
	['graphql'],
	['rest', 'restful', 'rest api', 'restful api'],
	['grpc'],
	['websocket', 'websockets'],
	['microservices', 'microservice'],

	// Data stores
	['postgresql', 'postgres', 'psql', 'pg'],
	['mysql'],
	['mongodb', 'mongo'],
	['redis'],
	['elasticsearch', 'elastic', 'opensearch'],
	['dynamodb'],
	['cassandra'],
	['sqlite'],
	['oracle db', 'oracle database'],
	['sql server', 'mssql', 'microsoft sql server'],
	['snowflake'],
	['bigquery'],
	['redshift'],
	['neo4j'],

	// Cloud and infrastructure
	['aws', 'amazon web services'],
	['gcp', 'google cloud', 'google cloud platform'],
	['azure', 'microsoft azure'],
	['docker', 'containerization', 'containers'],
	['kubernetes', 'k8s'],
	['terraform'],
	['ansible'],
	['jenkins'],
	['github actions'],
	['gitlab ci'],
	['circleci'],
	['ci/cd', 'cicd', 'continuous integration', 'continuous delivery', 'continuous deployment'],
	['serverless', 'lambda', 'aws lambda'],
	['nginx'],
	['kafka', 'apache kafka'],
	['rabbitmq'],
	['helm'],
	['prometheus'],
	['grafana'],
	['datadog'],
	['splunk'],

	// Data and machine learning
	['machine learning', 'ml'],
	['deep learning', 'dl'],
	['artificial intelligence', 'ai'],
	['natural language processing', 'nlp'],
	['computer vision', 'cv'],
	['tensorflow', 'tf'],
	['pytorch', 'torch'],
	['scikit-learn', 'sklearn', 'scikit learn'],
	['pandas'],
	['numpy'],
	['spark', 'apache spark', 'pyspark'],
	['hadoop'],
	['airflow', 'apache airflow'],
	['dbt'],
	['tableau'],
	['power bi', 'powerbi'],
	['etl', 'elt'],
	['data warehouse', 'data warehousing'],
	['data pipeline', 'data pipelines'],
	['llm', 'large language model', 'large language models'],

	// Practices and tooling
	['git', 'version control'],
	['agile', 'scrum'],
	['kanban'],
	['jira'],
	['tdd', 'test driven development', 'test-driven development'],
	['unit testing', 'unit tests'],
	['integration testing', 'integration tests'],
	['code review', 'code reviews'],
	['distributed systems'],
	['system design'],
	// Surfaced by auditing what a phrase-extraction pass would have caught that the taxonomy
	// missed. These are the genuine recall gaps; the rest of that pass was noise.
	['api design'],
	['backend services', 'backend service'],
	['event streaming', 'event streaming platform', 'stream processing'],
	['computer science', 'cs degree'],
	['observability', 'monitoring'],
	['security', 'infosec', 'information security'],
	['oauth', 'oauth2'],
	['linux', 'unix']
];
