import type { ScoreResult } from '$engine/types/scoring';

/**
 * LRU response cache (PRD §8.5).
 *
 * Behind an interface for the same reason as the rate limiter: on Vercel Edge the hit rate
 * across many short-lived isolates is close to zero, so this is a local optimisation rather
 * than the cost control the PRD assumes.
 */

export interface CachedResponse {
	results: ScoreResult[];
	provider: string;
}

export interface ResponseCache {
	get(key: string): CachedResponse | null;
	set(key: string, value: CachedResponse): void;
	readonly size: number;
}

export const CACHE_MAX_ENTRIES = 200;
export const CACHE_TTL_MS = 24 * 60 * 60 * 1000;

/**
 * Bumped whenever the prompt changes shape. Without it, a prompt edit silently keeps serving
 * answers generated by the previous version for a full day.
 */
export const PROMPT_VERSION = 'v1';

/**
 * Weaker providers get a shorter TTL.
 *
 * PRD §8.5 keyed only on the prompt, so a degraded Groq answer produced during a Gemini
 * outage would be served for 24 hours after Gemini recovered.
 */
const TTL_BY_TIER: Readonly<Record<string, number>> = {
	primary: CACHE_TTL_MS,
	fallback: 60 * 60 * 1000
};

interface Entry {
	value: CachedResponse;
	expiresAt: number;
}

export class MemoryResponseCache implements ResponseCache {
	private readonly entries = new Map<string, Entry>();

	constructor(
		private readonly maxEntries = CACHE_MAX_ENTRIES,
		private readonly now: () => number = Date.now
	) {}

	get size(): number {
		return this.entries.size;
	}

	get(key: string): CachedResponse | null {
		const entry = this.entries.get(key);
		if (!entry) return null;

		if (entry.expiresAt <= this.now()) {
			this.entries.delete(key);
			return null;
		}

		// Re-insert so the Map's insertion order stays LRU-ordered.
		this.entries.delete(key);
		this.entries.set(key, entry);
		return entry.value;
	}

	set(key: string, value: CachedResponse, tier: 'primary' | 'fallback' = 'primary'): void {
		if (this.entries.size >= this.maxEntries) {
			const oldest = this.entries.keys().next();
			if (!oldest.done) this.entries.delete(oldest.value);
		}

		this.entries.set(key, {
			value,
			expiresAt: this.now() + (TTL_BY_TIER[tier] ?? CACHE_TTL_MS)
		});
	}
}

/**
 * Cache key. Uses WebCrypto rather than node:crypto because this runs on Edge.
 *
 * The provider tier is part of the key so a fallback answer never masquerades as a primary
 * one on a later request.
 */
export async function cacheKey(prompt: string, tier: string): Promise<string> {
	const data = new TextEncoder().encode(`${PROMPT_VERSION}:${tier}:${prompt}`);
	const digest = await crypto.subtle.digest('SHA-256', data);

	return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, '0')).join('');
}
