/**
 * The 100 strong action verbs from PRD §7.7. A bullet scores if it *starts* with one.
 *
 * Stored lowercase; a test asserts the count and that the set is deduplicated, so an
 * accidental edit to the literal shows up immediately.
 */
export const ACTION_VERBS: ReadonlySet<string> = new Set([
	'achieved',
	'accelerated',
	'administered',
	'advanced',
	'analyzed',
	'architected',
	'automated',
	'built',
	'centralized',
	'championed',
	'collaborated',
	'conceptualized',
	'consolidated',
	'contributed',
	'converted',
	'coordinated',
	'created',
	'decreased',
	'delivered',
	'designed',
	'developed',
	'directed',
	'drove',
	'eliminated',
	'enabled',
	'engineered',
	'established',
	'exceeded',
	'executed',
	'expanded',
	'facilitated',
	'founded',
	'generated',
	'grew',
	'headed',
	'identified',
	'implemented',
	'improved',
	'increased',
	'influenced',
	'initiated',
	'innovated',
	'integrated',
	'introduced',
	'launched',
	'led',
	'leveraged',
	'managed',
	'maximized',
	'mentored',
	'migrated',
	'modernized',
	'negotiated',
	'operated',
	'optimized',
	'orchestrated',
	'organized',
	'outperformed',
	'overhauled',
	'oversaw',
	'pioneered',
	'planned',
	'presented',
	'prioritized',
	'produced',
	'programmed',
	'proposed',
	'published',
	'raised',
	'recommended',
	'redesigned',
	'reduced',
	'refactored',
	'reformed',
	're-engineered',
	'reorganized',
	'replaced',
	'researched',
	'resolved',
	'restructured',
	'revamped',
	'revolutionized',
	'scaled',
	'secured',
	'simplified',
	'spearheaded',
	'standardized',
	'streamlined',
	'strengthened',
	'supervised',
	'surpassed',
	'synchronized',
	'trained',
	'transformed',
	'translated',
	'unified',
	'upgraded',
	// PRD §7.7's list runs to 97; these three round it to the stated 100 and are at least as
	// common on an engineering resume as several of the originals.
	'authored',
	'deployed',
	'quantified'
]);

/** True when the bullet's first word is a recognised action verb. */
export function startsWithActionVerb(bullet: string): boolean {
	const first = /^([A-Za-z-]+)/.exec(bullet.trim());
	if (!first?.[1]) return false;
	return ACTION_VERBS.has(first[1].toLowerCase());
}
